### ISSUE TITLE
SSL support on ActiveMQ

### ISSUE THREAD

**Issue by mattpangaro** [klyashko/jms-messenger#1]
Maybe there's already a way to do this, but would be great if this could connect to an ActiveMQ broker that will only accept SSL connections, like: ssl://10.1.1.2:61616.

Thanks for the work on this!

**Comment by klyashko** [comment]
@mattpangaro new version is available in the repository. Can you check it and I'll close this ticket.

**Comment by mattpangaro** [comment]
@klyashko new version connected beautifully! On the new SSL tab, I figured out that it was full path to the stores, but a hint on screen, or better yet a browse button, would make it easier for new users.

Thanks for the speedy improvement!
