### ISSUE TITLE
Remove domain validation

### ISSUE THREAD

**Issue by mistic100** [klyashko/jms-messenger#11]
In my company we use custom DNS for all our services, the MQ I am trying to connect to is for instance "mq-1.inte.local"

Because of the domain validation performed here https://github.com/klyashko/jms-messenger/blob/6c8a82093889ac50de1f3ccc19bb3f3a40b20066/src/main/java/com/idea/tools/view/ServerEditPanel.java#L142
I cannot connect to this host.

**Comment by klyashko** [comment]
Hi @mistic100 .
Plugin with fix is available in the repository.
