### ISSUE TITLE
Version 2 no longer runs with IntelliJ default JDK runtime

### ISSUE THREAD

**Issue by tnleeuw** [klyashko/jms-messenger#14]
I don't know why the JDK requirement for version 2 was upgraded to JDK13, but to the best of my knowledge IntelliJ is installed by default with JDK11.
So out of the box, the new version of the plugin doesn't work anymore.

**Comment by klyashko** [comment]
Hi @tnleeuw Thanks for the information. I'll check the problem.

**Comment by klyashko** [comment]
@tnleeuw the fix is pushed to the repo

**Comment by tnleeuw** [comment]
Thank you!

**Comment by klyashko** [comment]
@tnleeuw the fix is available for download.

**Comment by tnleeuw** [comment]
Thanks, I do not yet see it when checking for updates but I trust it to be visible soon!

**Comment by klyashko** [comment]
@tnleeuw I've got the email about approval for the update yesterday in the evening. And I already see the update in the repo. So yes, it should be visible for you as well.

**Comment by tnleeuw** [comment]
After I tried re-enabling the plugin and restarting IntelliJ, the new version eventually was visible.
Thank you!

**Comment by klyashko** [comment]
That's probably was the reason. Idea doesn’t check updates for disabled plugins.
