### ISSUE TITLE
JMS Messanger display malfunction

### ISSUE THREAD

**Issue by smoczyna** [klyashko/jms-messenger#6]
JMS Tab/Widget windows doesn't resize properly in LInux version. Windows can be resized but teh content of the window stays as is and it is too small to see all elements and any operations like add new JMS is not possible.

**Comment by smoczyna** [comment]
![image](https://user-images.githubusercontent.com/3852400/61583257-62bde180-ab2d-11e9-985e-11247369863a.png)

**Comment by smoczyna** [comment]
this window works fine in windows, at least on my machine

**Comment by klyashko** [comment]
Hi @smoczyna. 
Thank you for the information. I'll try to check it in the nearest time.

**Comment by klyashko** [comment]
Hello @smoczyna .
The new version 1.3.0 has been released. Can you still have this issue?

**Comment by smoczyna** [comment]
Unfortunately yes, the inner frame is still not resizing together with the
main window and it is so small that make any operation impossible, please
see teh screenshot below

[image: image.png]

**Comment by klyashko** [comment]
I think it will take some time for me to resolve this issue.

**Comment by klyashko** [comment]
What about settings window? There is also a form for adding new servers. Do you have any problems with that?

**Comment by smoczyna** [comment]
Yes, it's the same, really small rectangle inside the settings window.

**Comment by klyashko** [comment]
What java version do you use to run ide on linux?

**Comment by smoczyna** [comment]
It is running on its own JVM, exactly as recommended. it's OpenJDK by
JetBrains if I remember correctly.

**Comment by klyashko** [comment]
Do you have opportunity to try to run ide on Oracle JDK?

**Comment by smoczyna** [comment]
I used to do that but had serious issues with IDE (for instance I couldn't
start it at all) so i switched to its native one as recommended by
Jetbrains.
It work like that since then.
For me your plugin issue looks rather like rendering problem. It should use
flex container or so to span for the size of the window.
