### ISSUE TITLE
Feature request: support of Open MQ 

### ISSUE THREAD

**Issue by davidobber** [klyashko/jms-messenger#8]
[OpenMQ](https://javaee.github.io/openmq/) is a JMS Server used by [Payara Application Server](https://www.payara.fish/) (a "spin-off" of Glassfish 4). 

The request is to handle this JMS Server.

**Comment by klyashko** [comment]
Hi. @davidobber. I'll check this possibility in the next few days.

**Comment by klyashko** [comment]
Hi @davidobber. As I see, OpenMQ isn't new tech and there is no much documentation available. Are you able to provide links on documentation, how to start the service for testing purpose, preferably in Docker container and how to connect to it from java client? Without this information I may not able to proceed.

**Comment by davidobber** [comment]
Hi, unfortunately I haven't specific documentation about it. I just know
that it is provided with Glassfish and Payara as the default JMS management
system. Never mind. Close the issue.


Il giorno dom 1 mar 2020 alle ore 16:00 Kirill <notifications@github.com>
ha scritto:
